
| Outcome         | Reason                       | Subreason                                           | Definition                                                                                                                                   | Technical                                                                         |
| --------------- | ---------------------------- | --------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| Booked          | Booked                       | Booked                                              | Appointment was successfully scheduled. Job type breakdown (HVAC, plumbing, etc.) is a separate dimension and not part of reason/sub-reason. | New job created in CRM by the Netic Agent                                         |
| Unbooked        | Timing objection             | Too Late                                            | Earliest available appointment is too far out for the customer                                                                               | Timing objection classifier                                                       |
|                 |                              | Emergency Service Unavailable                       | Customer needed emergency service but none was available                                                                                     | Timing objection classifier                                                       |
|                 |                              | Customer Timing Conflict                            | Other scheduling conflicts — e.g. customer can only do weekends or late afternoons                                                           | Timing objection classifier                                                       |
|                 | Price objection              | Price objection                                     | Customer abandoned the call after learning the price                                                                                         | Price objection classifier                                                        |
|                 | Need to speak to third party | Family Member                                       | Customer wants to check with a family member before committing                                                                               | Service objection classifier                                                      |
|                 | Went with Other              | Went with Competitor (Pricing)                      | Customer decided to go to a competitor due to pricing                                                                                        | Competitor objection classifier                                                   |
|                 |                              | Went with Competitor (Timing)                       | Customer decided to go to a competitor due to timing                                                                                         | Competitor objection classifier                                                   |
|                 |                              | Went with Competitor (Other)                        | Customer decided to go to a competitor for other/unclear reasons                                                                             | Competitor objection classifier                                                   |
|                 |                              | Will Try to Solve on Their Own                      | Customer decided to solve the problem DIY or via friend, family, or neighbor                                                                 | Competitor objection classifier                                                   |
|                 | AI objection                 | AI objection                                        | Customer refused to continue with AI and no transfer was completed                                                                           | Sentiment classifier (negative) + AI frustration signal                           |
|                 | Friction                     | Information Confirmation Issues                     | Booking failed due to trouble confirming the customer's details (address, name, etc.)                                                        | Sentiment classifier (negative) + confirmation failure signal                     |
|                 |                              | Too Many Questions                                  | Customer dropped off citing frustration with the number of questions                                                                         | Sentiment classifier (negative) + excessive questions signal                      |
|                 |                              | General Frustration in Conversation                 | Customer showed general frustration                                                                                                          | Sentiment classifier (negative) + general frustration signal                      |
|                 | Disconnected                 | Other                                               | Call ended without a clear reason — no objection signal identified                                                                           | No objection classifier fired on an unbooked call                                 |
| Handled         | Price shopping               | Price shopping                                      | Caller's goal was to gather pricing info with no intent to book                                                                              | Intent classifier (price shopping sub-intent)                                     |
|                 | Need to speak to third party | Need to speak to Landlord                           | Caller needs landlord sign-off; treated as Handled since it's a service-blocking constraint, not just a timing issue                         | Service objection classifier                                                      |
|                 |                              | No Authority to Book - Other                        | Caller cannot authorize the booking themselves                                                                                               | Service objection classifier                                                      |
|                 | Service not offered          | Outside Service Area                                | Customer intended to book but is outside the service area                                                                                    | Service objection classifier                                                      |
|                 |                              | Unsupported Job or Trade                            | Customer intended to book but the job or trade is not supported                                                                              | Service objection classifier                                                      |
|                 | Appointment confirmed        | Appointment confirmed                               | Customer confirmed their upcoming appointment time                                                                                           | Intent + outcome classifiers                                                      |
|                 | Appointment rescheduled      | Appointment rescheduled                             | Agent successfully moved an existing appointment to a new date or time                                                                       | Intent + outcome classifiers                                                      |
|                 | Appointment checked          | Appointment checked                                 | Customer checked on their appointment and asked about its details                                                                            | Intent + outcome classifiers                                                      |
|                 | Appointment updated          | Appointment updated                                 | Customer added additional info for their upcoming appointment                                                                                | Intent + outcome classifiers                                                      |
|                 | Appointment cancellation     | Scheduling Conflicts                                | Cancelled existing appointment due to scheduling conflicts (e.g. sick, family emergency, other appointment)                                  | Intent classifier + timing objection classifier                                   |
|                 |                              | Went with Competitor (Pricing)                      | Cancelled existing appointment and went with a competitor for pricing reasons                                                                | Intent classifier + competitor objection classifier                               |
|                 |                              | Went with Competitor (Timing)                       | Cancelled existing appointment and went with a competitor for timing reasons                                                                 | Intent classifier + competitor objection classifier                               |
|                 |                              | Went with Competitor (Other)                        | Cancelled existing appointment and went with a competitor for other/unclear reasons                                                          | Intent classifier + competitor objection classifier                               |
|                 |                              | DIY Solve                                           | Cancelled existing appointment because the customer solved it themselves                                                                     | Intent classifier + competitor objection classifier                               |
|                 |                              | Problem Fixed Itself                                | Cancelled existing appointment because the problem fixed itself                                                                              | Intent classifier + competitor objection classifier                               |
|                 |                              | Cannot Afford                                       | Cancelled existing appointment because they could not afford it (cost too high, financing declined, insurance issues, etc.)                  | Intent classifier + price objection classifier                                    |
|                 |                              | Other Cancel Reason                                 | Cancelled for other/unknown reason                                                                                                           | Intent classifier (no specific objection signal on cancellation)                  |
|                 | General inquiry              | Business Hours or Location Serviced                 | Customer inquired about business hours or locations served                                                                                   | Intent classifier                                                                 |
|                 |                              | Trades or Technician Qualifications                 | Customer inquired about technician qualifications or trades serviced                                                                         | Intent classifier                                                                 |
|                 |                              | Partnerships inquiry                                | Caller inquired about business partnerships or referral arrangements                                                                         | Intent classifier                                                                 |
|                 |                              | Insurance or Payment Options                        | Customer inquired about insurance or payment options                                                                                         | Intent classifier                                                                 |
|                 | Admin Questions              | Billing                                             | Customer asked billing questions                                                                                                             | Intent classifier                                                                 |
|                 |                              | Membership                                          | Customer asked membership questions. Modifying membership is live transfer; getting membership details is TAKE A NOTE                        | Intent classifier                                                                 |
|                 |                              | Warranty                                            | Customer asked warranty questions                                                                                                            | Intent classifier                                                                 |
|                 |                              | Permits, Certifications, and Government Inspections | Customer asked about permits, certifications, or other government-related questions                                                          | Intent classifier                                                                 |
|                 |                              | Career inquiry                                      | Caller inquiring about a career opportunity                                                                                                  | Intent classifier                                                                 |
|                 | Spam call                    | Spam call                                           | The call is spam or irrelevant — gibberish, prank calls, sales/telemarketing, auto-reply, or unrelated to the business                       | Intent classifier (excused — spam)                                                |
|                 | Excused                      | Wrong Number                                        | Caller called the wrong number                                                                                                               | Intent classifier (excused)                                                       |
|                 |                              | Telemarketer                                        | Caller is a salesperson / telemarketer                                                                                                       | Intent classifier (excused)                                                       |
|                 |                              | Internal Call                                       | Call between two internal phone numbers (employees or technicians)                                                                           | Intent classifier (excused)                                                       |
|                 |                              | Other                                               | Call had no significant interaction but doesn't fit the above                                                                                | Intent classifier (excused)                                                       |
| Not enough info | No Response                  | No Response                                         | No meaningful interaction occurred — the call had no transcript or the caller provided no substantive response                               | No transcript recorded, or intent classifier returns no meaningful interaction    |
|                 | Requested call back          | Requested call back                                 | Caller hung up quickly after indicating they would call back                                                                                 | Intent classifier (excused — callback) with no transfer completed                 |
|                 | Requested human              | Preference for Human                                | Caller immediately asked for a human with no booking context, and no transfer was completed                                                  | Intent classifier (excused — requested representative) with no transfer completed |

--- 
## Transfer

Transfer reasons vary significantly by tenant configuration — the entries below are a representative sample, not exhaustive.

Transfers are further broken down by escalation type: **live transfer** (customer reached a CSR in real time) vs. **non-live escalation** (a note was taken for follow-up, or the call escalated after hangup).

|          |                                                                     |                                                                                                                                                                                                                                        |                                                                                                                                                                                        |
| -------- | ------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Outcome  | Reason                                                              | Subreason                                                                                                                                                                                                                              | Definition                                                                                                                                                                             |
| Transfer | Requested human                                                     | Preference for Human                                                                                                                                                                                                                   | Customer requested a human because they explicitly prefer humans, or do so immediately before significant conversation occurs                                                          |
|          |                                                                     | Need a Manager                                                                                                                                                                                                                         | Customer requested a supervisor, manager, or someone higher up to talk to                                                                                                              |
|          |                                                                     | Frustrated with AI                                                                                                                                                                                                                     | Customer requested a human because they were getting frustrated with AI                                                                                                                |
|          |                                                                     | Other                                                                                                                                                                                                                                  | Customer requested a human for an unknown reason                                                                                                                                       |
|          | Response to Outbound                                                | Outbound response                                                                                                                                                                                                                      | Caller missed a call from CXR / technician and is following up                                                                                                                         |
|          | Reschedule outbound response                                        |                                                                                                                                                                                                                                        | Caller specifically missed a call for rescheduling a job  <br>- Generic rescheduling outbound  <br>- Maintenance rescheduling outbound, if configured  <br>- Maintenance rescheduling outbound with an offer for credit, if configured |
|          | Admin Questions                                                     | Billing                                                                                                                                                                                                                                | Customer asked billing questions                                                                                                                                                       |
|          |                                                                     | Membership                                                                                                                                                                                                                             | Customer asked membership questions. Modifying membership is live transfer, getting membership details is TAKE A NOTE                                                                  |
|          |                                                                     | Warranty                                                                                                                                                                                                                               | Customer asked warranty questions                                                                                                                                                      |
|          |                                                                     | Permits, Certifications, and Government Inspections                                                                                                                                                                                    | Customer asked permits, certifications, and other government related questions                                                                                                         |
|          |                                                                     | Insurance                                                                                                                                                                                                                              | Customer asked insurance questions                                                                                                                                                     |
|          |                                                                     | Sensitive info                                                                                                                                                                                                                         | Customer needs to share sensitive info                                                                                                                                                 |
|          | Job type escalation rule                                            | Escalation Job Type                                                                                                                                                                                                                    | Process is defined to escalate inquired job type                                                                                                                                       |
|          |                                                                     | Job type Not Handled by Netic                                                                                                                                                                                                          | Job type not handled by Netic                                                                                                                                                          |
|          |                                                                     | <other custom rules>                                                                                                                                                                                                                   | Custom rules, e.g.  <br>- fireplace service  <br>- geothermal service  <br>- appliance service  <br>- duct work  <br>- etc.                                                            |
|          | Location type escalation rule                                       | Commercial                                                                                                                                                                                                                             | Caller requested service for a commercial property or location                                                                                                                         |
|          |                                                                     | Escalation Zones                                                                                                                                                                                                                       | Postal codes that require escalation zones                                                                                                                                             |
|          |                                                                     | Property Type                                                                                                                                                                                                                          | Caller mentioned a mobile home or other non-serviceable property type  <br>- mobile home  <br>- stacked / side-by-side condo                                                           |
|          |                                                                     | Address Validation Issues                                                                                                                                                                                                              | AI agent faced issues validating the customer's address against the database                                                                                                           |
|          |                                                                     | Rental inspections                                                                                                                                                                                                                     | Customer is calling for a rental inspection                                                                                                                                            |
|          |                                                                     | <custom rules>                                                                                                                                                                                                                         | Custom rules: e.g.  <br>- Meant to call other branch                                                                                                                                  |
|          | Scheduling escalation rules                                         | No availabilities                                                                                                                                                                                                                      | No availabilities were found                                                                                                                                                           |
|          |                                                                     | Appointment had transfer criteria                                                                                                                                                                                                      | Appointment had transfer criteria, e.g. attached to a dummy technician                                                                                                                 |
|          |                                                                     | Confirming appt requires transfer                                                                                                                                                                                                      | Appointment confirmation requires transfer                                                                                                                                             |
|          |                                                                     | <custom rules>                                                                                                                                                                                                                         | Other custom rules, e.g. specific third party leads, etc                                                                                                                               |
|          | Customer escalation rules                                           | Do not service                                                                                                                                                                                                                         | Customer has "Do Not Service" tag                                                                                                                                                      |
|          |                                                                     | Escalation tag                                                                                                                                                                                                                         | Customer has escalation tag                                                                                                                                                            |
|          |                                                                     | <custom rules>                                                                                                                                                                                                                         | Other custom rules, e.g. HOA                                                                                                                                                           |
|          | Parts related                                                       | Parts inquiry                                                                                                                                                                                                                          | Customer has an inquiry about parts  <br>- If customized, we may break out certain types of parts orders, e.g. filter changes and refrigerant recharges                                |
|          | Follow ups                                                          | Open Estimates                                                                                                                                                                                                                         | Caller following up on an open estimate                                                                                                                                                |
|          |                                                                     | In-Progress Work                                                                                                                                                                                                                       | Caller following up regarding in-progress work                                                                                                                                         |
|          |                                                                     | Recent installation                                                                                                                                                                                                                    | Caller following up on recent install                                                                                                                                                  |
|          |                                                                     | Forgotten tools and equipment                                                                                                                                                                                                          | TAKE A NOTE. Caller is reporting forgotten tools and equipment by technician.                                                                                                          |
|          | Mismatched information                                              | Name Mismatch                                                                                                                                                                                                                          | AI agent faced issues validating the customer's name against the database                                                                                                              |
|          |                                                                     | No Appointments Found                                                                                                                                                                                                                  | AI agent found no appointments for a customer who claimed they had an appointment scheduled                                                                                            |
|          |                                                                     | Appointment scheduled for the past                                                                                                                                                                                                     | AI agent found an appointment booked for the past, but not in-progress/completed                                                                                                       |
|          |                                                                     | Job already dispatched                                                                                                                                                                                                                 | Customer is trying to modify an appointment where a tech has already been dispatched                                                                                                   |
|          |                                                                     | Duplicate booking                                                                                                                                                                                                                      | Customer is trying to book a duplicate booking                                                                                                                                         |
|          |                                                                     | Existing appointment for new location/customer                                                                                                                                                                                         | Customer is trying to modify an appointment, but is a new address or customer                                                                                                          |
|          |                                                                     | Reschedule escalation                                                                                                                                                                                                                  | Issue with mismatched info for reschedule request                                                                                                                                      |
|          | Second appointment requested                                        |                                                                                                                                                                                                                                        | Customer requested two appointments to be booked                                                                                                                                       |
|          | Significant job modification                                        | Reinstate cancelled appointment                                                                                                                                                                                                        | Customer is asking to reinstate their already cancelled appointment                                                                                                                    |
|          |                                                                     | Change job type                                                                                                                                                                                                                        | Customer requests to make a significant change to existing appointment. E.g. entirely new trade or entirely new address.                                                               |
|          | Non-owner/occupant                                                  |                                                                                                                                                                                                                                        | Customer is a non-owner/occupant of their service location                                                                                                                             |
|          | Follow up required                                                  | Wants Other Modality                                                                                                                                                                                                                   | Customer requests to be contacted via different modality (call, text, email, etc.)                                                                                                     |
|          |                                                                     | Follow Up Requested                                                                                                                                                                                                                    | Customer explicitly asks for a follow up                                                                                                                                               |
|          | Customer concern                                                    | Injury or damage                                                                                                                                                                                                                       | Customer previously had a bad experience with business including injury or damage.                                                                                                     |
|          |                                                                     | Past appointment or interaction issues                                                                                                                                                                                                 | Customer previously had a bad experience with business during a past appointment or interaction. Can include more specific custom rules like "threatening to end relationship" if configured |
|          |                                                                     | Repeated frustration                                                                                                                                                                                                                   | Customer exhibits repeated frustration during conversation                                                                                                                             |
|          |                                                                     | Report a driver                                                                                                                                                                                                                        | Caller wants to report a driver/truck related to the company                                                                                                                           |
|          | Requested call back                                                 | Requested call back                                                                                                                                                                                                                    | Customer wants to be contacted via call                                                                                                                                                |
|          |                                                                     | Requested email                                                                                                                                                                                                                        | Customer wants to be contacted via email                                                                                                                                               |
|          |                                                                     | Requested text                                                                                                                                                                                                                         | Customer wants to be contacted via text                                                                                                                                                |
|          | Foreign language request                                            | Spanish request                                                                                                                                                                                                                        | Customer requests Spanish                                                                                                                                                              |
|          | Job-related Misc                                                    | Requested move up                                                                                                                                                                                                                      | Customer booked but wanted a sooner appt if one becomes available                                                                                                                      |
|          | Misc                                                                | Career inquiry                                                                                                                                                                                                                         | Caller inquiring about a career opportunity.                                                                                                                                           |
|          |                                                                     | Existing employee                                                                                                                                                                                                                      | Technician or other existing employee calls CSR agent.                                                                                                                                 |
|          |                                                                     | At office                                                                                                                                                                                                                              | Caller is at the office.                                                                                                                                                               |
|          |                                                                     | Guidance on equipment use                                                                                                                                                                                                              | TAKE A NOTE. Customer asks for guidance on using equipment.                                                                                                                            |
|          | Flags (no transfer)                                                 | Unbooked                                                                                                                                                                                                                               | Customer wants all unbooked calls to be flagged. Was noted as "transfer" for a while, but then we stopped doing so by setting mark_transfer = false                                    |
|          |                                                                     | High value job                                                                                                                                                                                                                         | Custom high value job flag. Similar to Unbooked, was marked as a transfer for a while                                                                                                  |
|          |                                                                     | No interaction                                                                                                                                                                                                                         | Custom rule to transfer any no interaction calls                                                                                                                                        |
|          | System event                                                        |                                                                                                                                                                                                                                        | Technical issue, e.g. max API tries for most routes, RR 500s, etc. We track more specific reasons, but bucket them together when showing to the customer                               |
|          | escalation rule                                                     |                                                                                                                                                                                                                                        | Custom escalation rule. This should be dead and broken out, but is here for historic reasons                                                                                           |
|          | Other                                                               |                                                                                                                                                                                                                                        | Did not fit any other category                                                                                                                                                         |

---

## Post-Transfer Interaction

Applies to calls where a transfer was initiated. Documents the outcome of the conversation that took place after the transfer.

| Category            | Reason                              | Sub-reason                                          | Definition                                                                                                                   | Technical                                                                      |
| ------------------- | ----------------------------------- | --------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ |
| Did Not Reach Human | Hit Voicemail                       | Hit Voicemail                                       | Transfer was placed but the customer's line went to voicemail; the CSR call was not answered                                 | Post-transfer event log detects voicemail                                      |
|                     | Confirmed Callback                  | Confirmed Callback                                  | A callback was scheduled or confirmed after the transfer                                                                     | Post-transfer event log detects confirmed callback                             |
|                     | Hung Up                             | Hung Up                                             | Transfer was placed but the customer hung up before reaching a CSR                                                           | Post-transfer event log: no interaction events, no classifier ran              |
| Booked Live         | Booked Live                         | Booked Live                                         | A job was created in the system during or immediately after the transfer                                                     | Job created in ServiceTitan during/after transfer                              |
| Booked Later        | Booked Later                        | Booked Later                                        | A job was booked within 7 days of the transfer and linked back to this interaction                                           | Job linked to this interaction within 7 days of transfer                       |
| Booked Unconfirmed  | Booked Unconfirmed                  | Booked Unconfirmed                                  | The post-transfer call sounds like a booking was completed, but no job was mechanically confirmed in the system              | Intent + outcome classifiers on post-transfer call; no CRM confirmation        |
| Unbooked            | Timing objection                    | Too Late                                            | Earliest available appointment is too far out for the customer                                                               | Post-transfer timing objection classifier                                      |
|                     |                                     | Emergency Service Unavailable                       | Customer needed emergency service but none was available                                                                     | Post-transfer timing objection classifier                                      |
|                     |                                     | Customer Timing Conflict                            | Other scheduling conflicts (scheduling conflict, weekend-only availability, etc.)                                            | Post-transfer timing objection classifier                                      |
|                     | Price objection                     | Price objection                                     | Customer abandoned after learning the price                                                                                  | Post-transfer price objection classifier                                       |
|                     | Need to speak to third party        | Need to speak to Family Member                      | Customer wants to check with a family member before booking                                                                  | Post-transfer service objection classifier                                     |
|                     | Went with Other                     | Went with Competitor (Pricing)                      | Customer went with a competitor due to pricing                                                                               | Post-transfer competitor objection classifier                                  |
|                     |                                     | Went with Competitor (Timing)                       | Customer went with a competitor due to timing                                                                                | Post-transfer competitor objection classifier                                  |
|                     |                                     | Went with Competitor (Other)                        | Customer went with a competitor for other/unclear reasons                                                                    | Post-transfer competitor objection classifier                                  |
|                     |                                     | Will Try to Solve on Their Own                      | Customer decided to DIY or use personal contacts                                                                             | Post-transfer competitor objection classifier                                  |
|                     | Follow Up                           | Customer will Call Back                             | Customer indicated they will call back to complete the booking                                                               | Post-transfer booking outcome classifier (callback/followup signal)            |
|                     |                                     | CSR Needs to Follow Up                              | CSR committed to following up with the customer to complete the booking                                                      | Post-transfer booking outcome classifier (internal follow-up signal)           |
|                     | Friction                            | Information Confirmation Issues                     | Booking failed due to issues confirming customer information (address, name, etc.)                                           | Post-transfer sentiment classifier (negative) + confirmation failure signal    |
|                     |                                     | Too Many Questions                                  | Customer exhibited fatigue or frustration due to the number of questions                                                     | Post-transfer sentiment classifier (negative) + excessive questions signal     |
|                     |                                     | General Frustration in Conversation                 | Customer showed general frustration                                                                                          | Post-transfer sentiment classifier (negative) + general frustration signal     |
|                     | Other                               | Interrupted                                         | Call was interrupted before booking could be completed                                                                       | Post-transfer booking outcome classifier (interrupted signal)                  |
|                     | Disconnected                        | Other                                               | Call ended without a booking and no clear reason could be identified                                                         | No objection classifier fired on an unbooked post-transfer call                |
| Handled             | Price shopping                      | Price shopping                                      | Caller gathered pricing information with no intent to book                                                                   | Post-transfer intent classifier (price shopping sub-intent)                    |
|                     | Need to speak to third party        | Need to speak to Landlord                           | Customer needs landlord approval; treated as Handled (service-blocking) rather than Unbooked                                 | Post-transfer service objection classifier                                     |
|                     |                                     | No Authority to Book - Other                        | Caller has no authority to authorize the booking                                                                             | Post-transfer service objection classifier                                     |
|                     | Service not offered                 | Outside service area                                |                                                                                                                              | Post-transfer service objection classifier                                     |
|                     |                                     | Unsupported Job or Trade                            |                                                                                                                              | Post-transfer service objection classifier                                     |
|                     | Job Requires Materials or More Info | Job Requires Materials or More Info                 | Job cannot be scheduled yet — needs materials, site prep, or more information before work can begin                          | Post-transfer booking outcome classifier (job not ready signal)                |
|                     | Other                               | Info Gathering - No Booking Intent                  | Caller was gathering information only with no intent to book                                                                 | Post-transfer booking outcome classifier (info only signal)                    |
|                     | Appointment confirmed               | Appointment confirmed                               |                                                                                                                              | Post-transfer intent + outcome classifiers                                     |
|                     | Appointment rescheduled             | Appointment rescheduled                             | CSR successfully rescheduled an existing appointment                                                                         | Post-transfer intent + outcome classifiers                                     |
|                     | Appointment checked                 | Appointment checked                                 |                                                                                                                              | Post-transfer intent + outcome classifiers                                     |
|                     | Appointment updated                 | Appointment updated                                 |                                                                                                                              | Post-transfer intent + outcome classifiers                                     |
|                     | Appointment cancellation            | Went with Competitor (Pricing)                      | Cancelled existing appointment and scheduled with a competitor for pricing reasons                                           | Post-transfer intent + competitor objection classifier                         |
|                     |                                     | Went with Competitor (Timing)                       | Cancelled existing appointment and scheduled with a competitor for timing reasons                                            | Post-transfer intent + competitor objection classifier                         |
|                     |                                     | Went with Competitor (Other)                        | Cancelled existing appointment and scheduled with a competitor for other/unclear reasons                                     | Post-transfer intent + competitor objection classifier                         |
|                     |                                     | Scheduling Conflicts                                | Cancelled existing appointment due to scheduling conflicts (sick, family emergency, other appointment, etc.)                 | Post-transfer intent + timing objection classifier                             |
|                     |                                     | DIY Solve                                           | Cancelled existing appointment because customer solved it themselves                                                         | Post-transfer intent + competitor objection classifier                         |
|                     |                                     | Problem Fixed Itself                                | Cancelled existing appointment because the problem fixed itself                                                              | Post-transfer intent + competitor objection classifier                         |
|                     |                                     | Cannot Afford                                       | Cancelled existing appointment because customer cannot afford it (cost too high, financing declined, insurance issues, etc.) | Post-transfer intent + price objection classifier                              |
|                     |                                     | Other Cancel Reason                                 | Cancelled for other/unclear reason not covered above                                                                         | Post-transfer intent classifier (no specific objection signal on cancellation) |
|                     | General inquiry                     | Business Hours or Location Serviced                 |                                                                                                                              | Post-transfer intent classifier                                                |
|                     |                                     | Trades or Technician Qualifications                 |                                                                                                                              | Post-transfer intent classifier                                                |
|                     |                                     | Partnerships inquiry                                | Caller inquired about business partnerships or referral arrangements                                                         | Post-transfer intent classifier                                                |
|                     |                                     | Insurance or Payment Options                        |                                                                                                                              | Post-transfer intent classifier                                                |
|                     | Admin Questions                     | Billing                                             |                                                                                                                              | Post-transfer intent classifier                                                |
|                     |                                     | Warranty                                            |                                                                                                                              | Post-transfer intent classifier                                                |
|                     |                                     | Membership                                          |                                                                                                                              | Post-transfer intent classifier                                                |
|                     |                                     | Permits, Certifications, and Government Inspections |                                                                                                                              | Post-transfer intent classifier                                                |
|                     |                                     | Career inquiry                                      |                                                                                                                              | Post-transfer intent classifier                                                |
|                     | Spam call                           | Spam call                                           |                                                                                                                              | Post-transfer intent classifier (excused — spam)                               |
|                     | No Response                         | No Response                                         |                                                                                                                              | Post-transfer intent classifier (excused — no response)                        |
|                     | Excused                             | Wrong Number                                        |                                                                                                                              | Post-transfer intent classifier (excused)                                      |
|                     |                                     | Telemarketer                                        |                                                                                                                              | Post-transfer intent classifier (excused)                                      |
|                     |                                     | Internal Call                                       |                                                                                                                              | Post-transfer intent classifier (excused)                                      |
|                     |                                     | Other                                               |                                                                                                                              | Post-transfer intent classifier (excused)                                      |
|                     | Requested call back                 | Requested call back                                 |                                                                                                                              | Post-transfer intent classifier                                                |
|                     | Misc                                | Existing employee                                   | Technician or other existing employee called in on the transferred call                                                      | Post-transfer intent classifier                                                |
|                     | Other                               | Preference for Human                                | Caller immediately requested a human on the transferred call                                                                 | Post-transfer intent classifier                                                |
|                     |                                     | Other                                               |                                                                                                                              | Post-transfer intent classifier                                                |
